# Schema validator for the laa pipeline
# author: Thomas Cokelaer


type: map
mapping:
    "sequana_wrappers":
        type: str
        required: true
    "input_directory":
        type: str
        required: True
    "input_pattern":
        type: str
        required: False
    "reference_file":
        type: str
        required: True
    "annotation_file":
        type: str
        required: True
    "data_type_choice":
        type: str
        required: True
    "extra_prefixes_to_strip":
        type: any
        required: False
    "apptainers":
        type: any
    "freebayes":
        type: map
        mapping:
            "do":
                type: bool
                required: True
            "ploidy":
                type: int
                required: True
            "options":
                type: str
                required: False
            "split_multiallelic":
                type: bool
                required: True
    "snpeff":
        type: map
        mapping:
            "do":
                type: bool
                required: True
            "build_options":
                type: str
                required: False
            "options":
                type: str
                required: True
    "kraken":
        type: map
        mapping:
            "do":
                type: bool
                required: True
            "databases":
                type: any
                required: False
    "freebayes_vcf_filter":
        type: map
        mapping:
            "do":
                type: bool
                required: True
            "freebayes_score":
                type: float
                required: True
            "frequency":
                type: float
                required: True
            "min_depth":
                type: int
                required: True
            "forward_depth":
                type: int
                required: True
            "reverse_depth":
                type: int
                required: True
            "strand_ratio":
                type: float
                required: True
    "raxml_mltree":
        type: map
        mapping:
            "N":
                type: int
                required: True
            "options":
                type: str
                required: True
    "raxml_bootstrap":
        type: map
        mapping:
            "N":
                type: int
                required: True
            "options":
                type: str
                required: True
    "multiqc":
        type: map
        mapping:
            "options":
                type: str
            "modules":
                type: str
            "config_file":
                type: str
            "input_directory":
                type: str
    "itol":
        type: map
        mapping:
            "do":
                type: bool
